"""Stub GitHub service used until Member 3 plugs in a real connector."""

from __future__ import annotations

from urllib.parse import urlparse

from app.core.exceptions import AppError
from app.services.github.base import GitHubCommitSummary, GitHubRepositoryData, GitHubService


class StubGitHubService(GitHubService):
    """Deterministic stub for Phase 0 scaffolding and local development."""

    async def validate_repository(self, repository_url: str) -> bool:
        parsed = urlparse(repository_url)
        if parsed.scheme not in {"http", "https"} or "github.com" not in (parsed.netloc or ""):
            return False
        parts = [part for part in parsed.path.split("/") if part]
        return len(parts) >= 2

    async def fetch_repository(self, repository_url: str) -> GitHubRepositoryData:
        if not await self.validate_repository(repository_url):
            raise AppError(
                "Invalid or unsupported GitHub repository URL",
                status_code=400,
                code="invalid_github_url",
            )

        parsed = urlparse(repository_url)
        parts = [part for part in parsed.path.split("/") if part]
        owner, name = parts[0], parts[1].removesuffix(".git")
        full_name = f"{owner}/{name}"

        return GitHubRepositoryData(
            repository_url=f"https://github.com/{full_name}",
            owner=owner,
            name=name,
            full_name=full_name,
            description="Stub repository data — replace with Member 3 GitHub connector",
            default_branch="main",
            readme_content=(
                f"# {name}\n\nThis is stub README content generated by StubGitHubService.\n"
                "Member 3 should replace this service with a real GitHub API implementation.\n"
            ),
            structure=["README.md", "src/", "docs/", "package.json"],
            important_files=["README.md", "package.json"],
            languages={"TypeScript": 70, "Python": 30},
            topics=["hackathon", "project-dna"],
            commit_summary=[
                GitHubCommitSummary(
                    sha="stub0001",
                    message="Initial commit",
                    author="stub",
                    date="2026-01-01T00:00:00Z",
                )
            ],
            stars=0,
            forks=0,
            raw={"source": "stub"},
        )
