"""Stub GitHub service used until Member 3 plugs in a real connector."""

from __future__ import annotations

from urllib.parse import urlparse

from app.core.exceptions import AppError
from app.services.github.base import GitHubCommitSummary, GitHubRepositoryData, GitHubService


class StubGitHubService(GitHubService):
    """Deterministic stub for Phase 0 scaffolding and local development."""

    async def validate_repository(self, repository_url: str) -> bool:
        parsed = urlparse(repository_url)
        if parsed.scheme not in {"http", "https"} or "github.com" not in (parsed.netloc or ""):
            return False
        parts = [part for part in parsed.path.split("/") if part]
        return len(parts) >= 2

    async def fetch_repository(self, repository_url: str) -> GitHubRepositoryData:
        if not await self.validate_repository(repository_url):
            raise AppError(
                "Invalid or unsupported GitHub repository URL",
                status_code=400,
                code="invalid_github_url",
            )

        parsed = urlparse(repository_url)
        parts = [part for part in parsed.path.split("/") if part]
        owner, name = parts[0], parts[1].removesuffix(".git")
        full_name = f"{owner}/{name}"

        return GitHubRepositoryData(
            repository_url=f"https://github.com/{full_name}",
            owner=owner,
            name=name,
            full_name=full_name,
            description="Stub repository data — replace with Member 3 GitHub connector",
            default_branch="main",
            readme_content=(
                f"# {name}\n\n"
                "This is stub README content generated by StubGitHubService.\n"
                "The project uses JWT authentication, a FastAPI backend, and a React frontend.\n"
                "Architecture overview: API layer, services, MongoDB persistence, and RAG chat.\n"
                "Deployment can use Docker Compose for local demos.\n"
                "Testing includes pytest coverage for auth, indexing, and chat flows.\n"
            ),
            structure=[
                "README.md",
                "src/",
                "docs/",
                "docs/architecture.md",
                "task.md",
                "spec.md",
                "package.json",
            ],
            important_files=["README.md", "package.json", "docs/architecture.md", "task.md", "spec.md"],
            documentation_files=[
                {
                    "path": "docs/architecture.md",
                    "content": (
                        "# Architecture\n\n"
                        "The system has a FastAPI backend, React frontend, MongoDB, and Qdrant.\n"
                        "JWT protects secured endpoints. RAG retrieves document chunks for chat.\n"
                    ),
                },
                {
                    "path": "task.md",
                    "content": (
                        "# Tasks\n\n"
                        "Implement authentication, document ingestion, indexing, and AI chat.\n"
                    ),
                },
                {
                    "path": "spec.md",
                    "content": (
                        "# Spec\n\n"
                        "Project DNA is an AI Knowledge Twin for software teams.\n"
                        "It indexes repositories and documents for grounded answers.\n"
                    ),
                },
            ],
            languages={"TypeScript": 70, "Python": 30},
            topics=["hackathon", "project-dna"],
            commit_summary=[
                GitHubCommitSummary(
                    sha="stub0001",
                    message="Initial commit",
                    author="stub",
                    date="2026-01-01T00:00:00Z",
                )
            ],
            stars=0,
            forks=0,
            raw={"source": "stub"},
        )

    async def fetch_documentation_files(
        self,
        repository_url: str,
        structure: list[str] | None = None,
    ) -> list[dict[str, str]]:
        data = await self.fetch_repository(repository_url)
        return list(data.documentation_files or [])
